### ISSUE TITLE
Use more sounds for piano

### ISSUE THREAD

**Issue by surikov** [emanchado/music-explorer#2]
Use more sounds from https://www.npmjs.com/package/midi-sounds-react

**Comment by emanchado** [comment]
Hi!

Thanks for your report! I'm wondering, what's the idea behind this? Simply give the user the possibility to use different sounds/instruments, or something else?

Music explorer is not quite designed to be "played" as an instrument, it's more a way to understand the relationship between notes, scales, and chords. So I'm not sure how useful it would be to be able to choose between different samples...

**Comment by surikov** [comment]
Now you can use different samples to illustrate different instruments. For example, guitar chords do not sound like piano chords.

**Comment by emanchado** [comment]
Aha, I see. I'm not sure I see enough value in that to actually make the change :-( Especially since the voicings I use for the chords are pretty simplistic and only make sense for a piano. Like, most of them would actually be impossible to play on a guitar with standard tuning :-(

I'll close this tentatively, as I don't think I'll implement it. But thanks again for your interest and your report!
